async (page) => {
  await page.goto('http://localhost:7862');
  await page.getByRole('tab', {name:'一键研报',exact:true}).click();
  await page.setViewportSize({width:1280,height:900});
  await page.getByRole('tab',{name:'🎯 估值',exact:true}).click();
  const heading = page.getByRole('button',{name:'解释：财报利润桥',exact:true});
  await heading.hover();
  const tip=page.locator('#term-tooltip');
  await tip.waitFor({state:'visible'});
  if (!(await tip.innerText()).includes('财报实绩')) throw new Error('Missing bridge explanation');
  await heading.click();
  await page.mouse.move(1,1);
  if (!await tip.isVisible()) throw new Error('Pinned explanation disappeared');
  await page.keyboard.press('Escape');
  await tip.waitFor({state:'hidden'});
  await page.keyboard.press('Tab');
  await heading.focus();
  await tip.waitFor({state:'visible'});
  await page.keyboard.press('Escape');
  await page.getByRole('textbox',{name:'股票名称或代码'}).fill('601899');
  await page.getByRole('button',{name:'加载利润数据',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#profit_meta')?.textContent.includes('紫金矿业'));
  await page.getByRole('button',{name:/解释：.*勾稽/}).first().hover();
  await tip.waitFor({state:'visible'});
  await page.screenshot({path:'output/playwright/glossary-desktop.png'});
  await page.keyboard.press('Escape');
  await page.getByRole('tab',{name:'经营情景',exact:true}).click();
  const model=page.getByRole('combobox',{name:'经营模型',exact:true});
  await model.fill('外购精矿冶炼');
  await page.getByRole('option',{name:'外购精矿冶炼',exact:true}).click();
  await page.waitForFunction(()=>[...document.querySelectorAll('label .term-help')].some(b=>b.dataset.terms.includes('TC')));
  const tcHelp=page.locator('label .term-help[data-terms*="TC"]').first();
  await tcHelp.click();
  if (!(await tip.innerText()).includes('美元/干吨')) throw new Error('Wrong TC units');
  await page.keyboard.press('Escape');
  await model.fill('金属加工及功能材料');
  await page.getByRole('option',{name:'金属加工及功能材料',exact:true}).click();
  await page.waitForFunction(()=>![...document.querySelectorAll('label .term-help')].some(b=>b.getClientRects().length&&b.dataset.terms.includes('TC')));
  const yieldHelp=page.locator('label .term-help[data-terms*="成材率"]').first();
  await page.setViewportSize({width:390,height:844});
  await yieldHelp.click();
  await tip.waitFor({state:'visible'});
  if (!(await tip.innerText()).includes('1.25')) throw new Error('Missing practical example');
  const bounds=await tip.boundingBox();
  if(bounds.x<0||bounds.x+bounds.width>390||bounds.y<0||bounds.y+bounds.height>844) throw new Error('Tooltip overflow');
  await page.screenshot({path:'output/playwright/glossary-mobile.png'});
  await page.getByRole('button',{name:'计算情景',exact:true}).click();
  await tip.waitFor({state:'hidden'});
  return {desktop:true,mobile:true,keyboard:true,dynamicModel:true};
}
